Repository caicloud/nirvana, pull requests merged in 2018-02, with the labels that each got.

#167 feat(config): add tests
  config/center_test.go
  config/config.go
  config/config_test.go
Labels: approved, area/test, lgtm, release-note, size/L

#165 fix(definition): remove builder pattern
  definition/definition.go
  definition/definition_test.go
  definition/helper.go
  examples/api-basic/api/v1/app.go
  examples/api-basic/api/v1/install.go
  examples/api-basic/api/v2/app.go
  examples/api-basic/api/v2/install.go
  examples/stream/api/v1/install.go
  examples/stream/api/v1/stream.go
Labels: approved, kind/cleanup, lgtm, release-note, size/L

#166 chore(cli): remove cli
  Makefile
  cli/OWNERS
  cli/README.md
  cli/cli.go
  cli/cli_test.go
  cli/config.go
  cli/config_generated.go
  cli/config_generated_test.go
  cli/config_test.go
  cli/flag.go
  cli/flag_test.go
  cli/flags_generated.go
  cli/flags_generated_test.go
  cli/util.go
  examples/cli/main.go
  hack/flag-gen/generators/flags.go
  hack/flag-gen/generators/viper.go
  hack/flag-gen/main.go
  hack/flag-gen/namer/namer.go
  hack/flag-gen/types/types.go
  hack/license/apache.go
Labels: approved, kind/cleanup, lgtm, release-note, size/XXL

#168 feat(examples): start with config.Command instead of nirvana.Server
  examples/api-basic/api/v1/install.go
  examples/api-basic/api/v2/install.go
  examples/api-basic/main.go
  examples/getting-started/basics/echo.go
  examples/getting-started/metrics/echo.go
  examples/getting-started/openapi/echo.go
  examples/getting-started/validator/echo.go
  examples/instrumentation/main.go
  examples/stream/api/v1/install.go
  examples/stream/main.go
  examples/tracing/main.go
Labels: approved, lgtm, release-note-none, size/L

#171 feat(openapi): change openapi tag from caicloud to nirvana
  README.md
  cmd/openapi-gen/generators/openapi_test.go
  cmd/openapi-gen/generators/tag.go
  cmd/openapi-gen/generators/tag_test.go
  examples/getting-started/openapi/pkg/api/types.go
  examples/openapi/README.md
  examples/openapi/pkg/api/v1/doc.go
Labels: approved, lgtm, release-note-none, size/M

#174 feat(readme): update plugin docs
  README.md
Labels: approved, lgtm, release-note, size/M

#175 docs(README): refine plugin README
  README.md
Labels: approved, lgtm, release-note-none, size/M

#176 feat(nirvana): remove parameters of nirvana.NewDefaultConfig()
  README.md
  config/config.go
  config/config_test.go
  examples/tracing/main.go
  nirvana.go
Labels: approved, lgtm, release-note, size/M

#177 docs(readme): update Configurer docs
  README.md
Labels: approved, lgtm, release-note-none, size/S
