Repository caicloud/nirvana, pull requests merged in 2018-04, with the labels that each got.

#196 feat(reqlog): add request logging plugin
  plugins/reqlog/reqlog.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#199 fix(service): fix wrong conflict definition check
  service/executor.go
  service/executor_test.go
Labels: approved, caicloud-cla: yes, lgtm, size/XS

#201 fix(service): Consumes and Produces of descriptor should affect current definitions
  service/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#204 feat(*): add ROADMAP.md and CONTRIBUTING.md
  CONTRIBUTING.md
  ROADMAP.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#205 chore(travis): upgrade go version to latest
  .travis.yml
  cmd/openapi-gen/builder/openapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#153 feat(tracing): add tracing hook
  plugins/tracing/hook.go
  plugins/tracing/tracing.go
  plugins/tracing/tracing_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#206 chore(build): update build/test tools
  .travis.yml
  Makefile
  hack/test_requirements.txt
  hack/update-all.sh
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M
