Repository caicloud/nirvana, pull requests merged in 2018-03, with the labels that each got.

#178 feat(server): allow to get service builder from nirvana server
  config/config.go
  nirvana.go
  plugins/tracing/tracing.go
Labels: approved, lgtm, release-note-none, size/L

#180 fix(nirvana): export Server.Builder
  nirvana.go
Labels: approved, lgtm, release-note-none, size/XS

#116 feat(tracing): Add tracing http transport
  plugins/tracing/client.go
  plugins/tracing/client_test.go
  plugins/tracing/server.go
  plugins/tracing/server_test.go
Labels: approved, lgtm, release-note-none, size/L

#179 feat(service): save abstract path into http context
  service/builder_test.go
  service/context.go
  service/executor.go
Labels: approved, lgtm, release-note-none, size/S

#181 refactor(tracing): change dir
  examples/tracing/main.go
  plugins/tracing/clients/http/http.go
  plugins/tracing/clients/http/http_test.go
  plugins/tracing/middleware/middleware.go
  plugins/tracing/middleware/middleware_test.go
  plugins/tracing/utils/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#170 fix(openapi): fix path item overriding problem
  cmd/openapi-gen/builder/openapi.go
  cmd/openapi-gen/builder/openapi_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#182 docs(openapi): add readme of OpenAPI section
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#184 fix(service): remove cache pool for http context
  service/builder.go
  service/context.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#185 feat(tracing): Add options
  examples/tracing/main.go
  plugins/tracing/tracing.go
  plugins/tracing/tracing_test.go
Labels: approved, caicloud-cla: yes, lgtm, size/S

#186 fix(service): treat Content-Length "" and "0" equally
  service/filter.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#187 feat(service): add more converters
  service/content.go
  service/content_test.go
  service/executor_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#188 fix(service): correct result of AutoParameterGenerator.Generate
  service/source.go
Labels: caicloud-cla: yes, lgtm, release-note, size/S

#191 fix(converter): return right pointer type
  service/content.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#190 feat(config): add PreConfigure and PostConfigure hooks
  config/config.go
  config/hooks.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#193 fix(config): fix PreConfigure wrong call
  config/hooks.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#194 feat(config): use table printer to format help message
  config/config.go
  config/config_test.go
  utils/printer/table.go
  utils/printer/table_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#195 feat(logger): add logger plugin
  log/default.go
  log/log.go
  log/silent.go
  log/std.go
  plugins/logger/logger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
