Repository caicloud/nirvana, pull requests merged in 2018-09, with the labels that each got.

#234 fix(project): passthrough VERSION and COMMIT from Makefile to Dockerfile
  cmd/nirvana/project/init.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#236 feat(apidocs): add plugin apidocs
  plugins/apidocs/OWNERS
  plugins/apidocs/apidocs.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#238 feat(readme): remove expired docs from README.md
  README.md
  docs/en/index.html
  docs/en/search_index.json
  docs/en/topics/cli.html
  docs/en/topics/error.html
  docs/en/topics/logging.md
  docs/en/topics/metrics.html
  docs/en/topics/openapi.html
  docs/en/topics/routes.html
  docs/en/topics/testing.html
  docs/en/topics/tracing.html
  docs/en/topics/validation.html
  docs/search_index.json
  docs/zh-hans/concepts/clients.html
  docs/zh-hans/concepts/configurer.html
  docs/zh-hans/concepts/context.html
  docs/zh-hans/concepts/cp.html
  docs/zh-hans/concepts/destination.html
  docs/zh-hans/concepts/error.html
  docs/zh-hans/concepts/filter.html
  docs/zh-hans/concepts/method.html
  docs/zh-hans/concepts/middleware.html
  docs/zh-hans/concepts/modifier.html
  docs/zh-hans/concepts/operator.html
  docs/zh-hans/concepts/plugin.html
  docs/zh-hans/concepts/prefab.html
  docs/zh-hans/concepts/source.html
  docs/zh-hans/guides/api.html
  docs/zh-hans/guides/client.html
  docs/zh-hans/guides/doc.html
  docs/zh-hans/guides/project.html
  docs/zh-hans/index.html
  docs/zh-hans/plugins/healthcheck.html
  docs/zh-hans/plugins/logger.html
  docs/zh-hans/plugins/metrics.html
  docs/zh-hans/plugins/profiling.html
  docs/zh-hans/plugins/reqlog.html
  docs/zh-hans/plugins/tracing.html
  docs/zh-hans/plugins/version.html
  docs/zh-hans/search_index.json
  docs/zh-hans/topics/command.html
  docs/zh-hans/topics/config.html
  docs/zh-hans/topics/converter.html
  docs/zh-hans/topics/definition.html
  docs/zh-hans/topics/errors.html
  docs/zh-hans/topics/log.html
  docs/zh-hans/topics/method.html
  docs/zh-hans/topics/nirvana.html
  docs/zh-hans/topics/rest.html
  docs/zh-hans/topics/router.html
  docs/zh-hans/topics/service.html
  docs/zh-hans/topics/start.html
  docs/zh-hans/topics/utils.html
  docs/zh-hans/topics/validator.html
  manuals/en/README.md
  manuals/en/SUMMARY.md
  manuals/en/topics/error.md
  manuals/en/topics/logging.md
  manuals/en/topics/testing.md
  manuals/en/topics/tracing.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL
