Repository caicloud/nirvana, pull requests merged in 2018-10, with the labels that each got.

#240 feat(project): add go.mod template and '--package-manager' flag to support go modules
  cmd/nirvana/project/init.go
  manuals/zh-hans/guides/project.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#242 chore(*): fix typos
  cmd/nirvana/buildutils/builder.go
  utils/api/analyzer.go
  utils/api/comments.go
  utils/api/definitions.go
  utils/builder/builder.go
  utils/project/config.go
  utils/project/path.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#243 fix: correct the wrong method
  examples/getting-started/validator/echo.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
