Repository caicloud/nirvana, pull requests merged in 2019-03, with the labels that each got.

#264 fix: init cmd path error on windows.
  utils/project/path.go
  utils/project/path_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#271 fix(utils/generators): fix generateAutoParameter does not generate ap…
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm

#266 fix(#265): fix format for generated api json file
  cmd/nirvana/api/api.go
Labels: approved, caicloud-cla: yes, cla: human-approved, lgtm, release-note-none, size/S
