Repository caicloud/nirvana, pull requests merged in 2019-01, with the labels that each got.

#257 chore: minor README update
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#258 chore: minor CONTRIBUTING update
  CONTRIBUTING.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#261 chore(linter): remove megacheck from the config of gometalinter
  config.json
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#260 feat(roadmap): add roadmap for v0.3
  ROADMAP.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
