Repository caicloud/nirvana, pull requests merged in 2020-05, with the labels that each got.

#313 feat(middleware): implemented two reqlog middlewares
  middlewares/reqlog/reqlog.go
  middlewares/reqlog/reqlog_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#314 feat(middleware): implemented metrics middleware
  metrics/metrics.go
  middlewares/metrics/metrics.go
  plugins/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#319 fix(utils): handle the nested element that may cause infinite recursion when generating API docs
  utils/api/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#321 chore(*): downgrade swagger-ui version to 3.22.2
  cmd/nirvana/api/api.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#324 fix(utils): fix wrong judgment method for nested types
  utils/api/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#326 fix(api-doc-gen): remove field 'raw' from api-doc-file
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#328 chore(*): bump swagger-ui version to v3.25.3
  cmd/nirvana/api/api.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#331 fix(api-docs): remove title in response schema
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
