Repository caicloud/nirvana, pull requests merged in 2020-04, with the labels that each got.

#303 chore: update OWNERS
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#301 feat(#300): support tags for generated API docs
  definition/definition.go
  service/builder.go
  utils/api/definitions.go
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#306 fix(#305): include pkg utils/api for projects' deps to generate api docs
  nirvana.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#307 feat(api): switch to swagger-ui
  cmd/nirvana/api/api.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#310 chore(docs): update API docs example image
  docs/en/index.html
  docs/en/search_index.json
  docs/en/topics/cli.html
  docs/en/topics/metrics.html
  docs/en/topics/openapi.html
  docs/en/topics/routes.html
  docs/en/topics/validation.html
  docs/search_index.json
  docs/zh-hans/concepts/clients.html
  docs/zh-hans/concepts/configurer.html
  docs/zh-hans/concepts/context.html
  docs/zh-hans/concepts/cp.html
  docs/zh-hans/concepts/destination.html
  docs/zh-hans/concepts/error.html
  docs/zh-hans/concepts/filter.html
  docs/zh-hans/concepts/method.html
  docs/zh-hans/concepts/middleware.html
  docs/zh-hans/concepts/modifier.html
  docs/zh-hans/concepts/operator.html
  docs/zh-hans/concepts/plugin.html
  docs/zh-hans/concepts/prefab.html
  docs/zh-hans/concepts/source.html
  docs/zh-hans/guides/api.html
  docs/zh-hans/guides/client.html
  docs/zh-hans/guides/doc.html
  docs/zh-hans/guides/images/docs.png
  docs/zh-hans/guides/project.html
  docs/zh-hans/index.html
  docs/zh-hans/plugins/healthcheck.html
  docs/zh-hans/plugins/logger.html
  docs/zh-hans/plugins/metrics.html
  docs/zh-hans/plugins/profiling.html
  docs/zh-hans/plugins/reqlog.html
  docs/zh-hans/plugins/tracing.html
  docs/zh-hans/plugins/version.html
  docs/zh-hans/search_index.json
  docs/zh-hans/topics/command.html
  docs/zh-hans/topics/config.html
  docs/zh-hans/topics/converter.html
  docs/zh-hans/topics/definition.html
  docs/zh-hans/topics/errors.html
  docs/zh-hans/topics/log.html
  docs/zh-hans/topics/method.html
  docs/zh-hans/topics/nirvana.html
  docs/zh-hans/topics/rest.html
  docs/zh-hans/topics/router.html
  docs/zh-hans/topics/service.html
  docs/zh-hans/topics/start.html
  docs/zh-hans/topics/utils.html
  docs/zh-hans/topics/validator.html
  manuals/zh-hans/guides/images/docs.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#309 refactor(metrics): standardize Prometheus metrics
  plugins/metrics/metrics.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#316 feat(service): add a new filter to support setting maxMemory manually when parsing request form
  service/filter.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
