Repository caicloud/nirvana, pull requests merged in 2020-10, with the labels that each got.

#361 fix(*): fix issue where generated client does not import third-party packages properly
  cmd/nirvana/api/api.go
  utils/generators/golang/generator.go
  utils/generators/golang/helper.go
  utils/generators/swagger/generator.go
  utils/generators/utils/definitions.go
  utils/project/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#362 feat(docs): update guides/client.md
  docs/en/index.html
  docs/en/search_index.json
  docs/en/topics/cli.html
  docs/en/topics/metrics.html
  docs/en/topics/openapi.html
  docs/en/topics/routes.html
  docs/en/topics/validation.html
  docs/search_index.json
  docs/zh-hans/concepts/clients.html
  docs/zh-hans/concepts/configurer.html
  docs/zh-hans/concepts/context.html
  docs/zh-hans/concepts/cp.html
  docs/zh-hans/concepts/destination.html
  docs/zh-hans/concepts/error.html
  docs/zh-hans/concepts/filter.html
  docs/zh-hans/concepts/method.html
  docs/zh-hans/concepts/middleware.html
  docs/zh-hans/concepts/modifier.html
  docs/zh-hans/concepts/operator.html
  docs/zh-hans/concepts/plugin.html
  docs/zh-hans/concepts/prefab.html
  docs/zh-hans/concepts/source.html
  docs/zh-hans/guides/api.html
  docs/zh-hans/guides/client.html
  docs/zh-hans/guides/doc.html
  docs/zh-hans/guides/project.html
  docs/zh-hans/index.html
  docs/zh-hans/plugins/healthcheck.html
  docs/zh-hans/plugins/logger.html
  docs/zh-hans/plugins/metrics.html
  docs/zh-hans/plugins/profiling.html
  docs/zh-hans/plugins/reqlog.html
  docs/zh-hans/plugins/tracing.html
  docs/zh-hans/plugins/version.html
  docs/zh-hans/search_index.json
  docs/zh-hans/topics/command.html
  docs/zh-hans/topics/config.html
  docs/zh-hans/topics/converter.html
  docs/zh-hans/topics/definition.html
  docs/zh-hans/topics/errors.html
  docs/zh-hans/topics/log.html
  docs/zh-hans/topics/method.html
  docs/zh-hans/topics/nirvana.html
  docs/zh-hans/topics/rest.html
  docs/zh-hans/topics/router.html
  docs/zh-hans/topics/service.html
  docs/zh-hans/topics/start.html
  docs/zh-hans/topics/utils.html
  docs/zh-hans/topics/validator.html
  manuals/zh-hans/guides/client.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#364 [release-0.2] feat(docs): update guides/client.md
  docs/en/index.html
  docs/en/search_index.json
  docs/en/topics/cli.html
  docs/en/topics/metrics.html
  docs/en/topics/openapi.html
  docs/en/topics/routes.html
  docs/en/topics/validation.html
  docs/search_index.json
  docs/zh-hans/concepts/clients.html
  docs/zh-hans/concepts/configurer.html
  docs/zh-hans/concepts/context.html
  docs/zh-hans/concepts/cp.html
  docs/zh-hans/concepts/destination.html
  docs/zh-hans/concepts/error.html
  docs/zh-hans/concepts/filter.html
  docs/zh-hans/concepts/method.html
  docs/zh-hans/concepts/middleware.html
  docs/zh-hans/concepts/modifier.html
  docs/zh-hans/concepts/operator.html
  docs/zh-hans/concepts/plugin.html
  docs/zh-hans/concepts/prefab.html
  docs/zh-hans/concepts/source.html
  docs/zh-hans/guides/api.html
  docs/zh-hans/guides/client.html
  docs/zh-hans/guides/doc.html
  docs/zh-hans/guides/project.html
  docs/zh-hans/index.html
  docs/zh-hans/plugins/healthcheck.html
  docs/zh-hans/plugins/logger.html
  docs/zh-hans/plugins/metrics.html
  docs/zh-hans/plugins/profiling.html
  docs/zh-hans/plugins/reqlog.html
  docs/zh-hans/plugins/tracing.html
  docs/zh-hans/plugins/version.html
  docs/zh-hans/search_index.json
  docs/zh-hans/topics/command.html
  docs/zh-hans/topics/config.html
  docs/zh-hans/topics/converter.html
  docs/zh-hans/topics/definition.html
  docs/zh-hans/topics/errors.html
  docs/zh-hans/topics/log.html
  docs/zh-hans/topics/method.html
  docs/zh-hans/topics/nirvana.html
  docs/zh-hans/topics/rest.html
  docs/zh-hans/topics/router.html
  docs/zh-hans/topics/service.html
  docs/zh-hans/topics/start.html
  docs/zh-hans/topics/utils.html
  docs/zh-hans/topics/validator.html
  manuals/zh-hans/guides/client.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#365 Revert "feat(*): support to add a http.Handler directly to the router"
  definition/definition.go
  examples/getting-started/any-method/main.go
  examples/getting-started/handler/main.go
  service/builder.go
  service/executor.go
  service/utils.go
  utils/api/definitions.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#366 Revert "[release-0.2] feat(*): support to add a http.Handler directly to the router"
  definition/definition.go
  examples/getting-started/any-method/main.go
  examples/getting-started/handler/main.go
  service/builder.go
  service/executor.go
  service/utils.go
  utils/api/definitions.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#367 fix(*): support the any method in client generation
  utils/generators/golang/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#370 feat(*): support serving API documentation pages when the server starts
  cmd/nirvana/api/api.go
  definition/helper.go
  examples/api-basic/main.go
  examples/api-basic/nirvana.yaml
  nirvana.go
  service/builder.go
  service/content.go
  utils/api/utils.go
  utils/generators/swagger/generator.go
  utils/generators/utils/utils.go
Labels: approved, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XL

#371 feat(cmd::api): work with go module
  utils/project/config.go
  utils/project/path.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#372 refactor(*): revert #370 and transfer the feature to a plugin
  cmd/nirvana/api/api.go
  examples/api-basic/main.go
  examples/getting-started/docs/apis/api.app.v1.json
  examples/getting-started/docs/apis/api.storage.v1alpha1.json
  examples/getting-started/docs/main.go
  nirvana.go
  plugins/apidocs/apidocs.go
  utils/generators/utils/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL

#377 chore(*): bump Swagger UI version to 3.36.0
  utils/api/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#375 feat(*): make init/client command work with go module
  cmd/nirvana/client/client.go
  utils/project/path.go
  utils/project/path_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M
