Repository caicloud/nirvana, pull requests merged in 2020-12, with the labels that each got.

#404 fix(rpc): disallow duplicated rpc path
  service/rpc/builder.go
  service/rpc/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#406 fix(config): add lock in Set function to avoid concurrent map writes when we run several servers at once
  config/center.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#408 chore(*): expose several functions for external use
  errors/errors.go
  service/handler.go
  service/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#410 fix(utils): fix an issue when the Auto parameter is a pointer in client generation
  utils/generators/golang/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#412 fix(*): handle the custom Destination in API docs and client generation
  rest/rest.go
  utils/generators/golang/helper.go
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#414 fix(utils): 确保 params 跟 results 的个数与函数的参数及返回值的个数相同
  utils/api/definitions.go
  utils/api/definitions_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#416 fix(generator): sort type names to make the package aliases deterministic
  utils/generators/golang/helper.go
  utils/generators/golang/helper_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#418 feat(swagger): support 'optional' tag for auto param
  service/source.go
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#420 feat(swagger): default tag in param also mean optional
  utils/generators/swagger/generator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#423 fix(client): fix bug of query cache (#381)
  rest/rest.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#425 chore: add underscore to proposedName when it is equal with type or be literal
  utils/generators/golang/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#427 fix(pkg): ignore the invoke when the struct container the field which has the same type with itself
  utils/generators/golang/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#429 fix(*): handle TOP RPC style error data
  errors/external.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
