Repository caicloud/nirvana, pull requests merged in 2020-11, with the labels that each got.

#378 fix(*): add the missing blank import in nirvana.go
  nirvana.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#381 perf(client): request support query in url
  rest/rest.go
  rest/rest_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#384 feat(*): switch to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#382 feat(*): support RPC style
  config/config.go
  definition/definition.go
  definition/restful.go
  definition/rpc.go
  examples/api-basic/api/v2/app_test.go
  examples/getting-started/any-method/main.go
  examples/getting-started/file/main.go
  examples/getting-started/handler/main.go
  examples/getting-started/rpc-style/main.go
  middlewares/reqlog/reqlog_test.go
  nirvana.go
  plugins/apidocs/apidocs.go
  rest/rest.go
  service/builder/builder.go
  service/context.go
  service/executor/errors.go
  service/executor/executor.go
  service/executor/middleware.go
  service/handler.go
  service/rest/builder.go
  service/rest/builder_test.go
  service/rest/errors.go
  service/rest/inspector.go
  service/rest/inspector_test.go
  service/rest/router/basic.go
  service/rest/router/errors.go
  service/rest/router/path.go
  service/rest/router/regexp.go
  service/rest/router/router.go
  service/rest/router/router_test.go
  service/rest/router/string.go
  service/router/utils.go
  service/rpc/builder.go
  service/rpc/errors.go
  service/source.go
  service/source_test.go
  service/types.go
  service/utils.go
  utils/api/api.go
  utils/api/definitions.go
  utils/builder/builder.go
  utils/unittest/unittest.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#387 chore(*): update GitHub Actions config
  .github/workflows/ci.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#390 feat(*): make multiple plugins support the RPC builder
  definition/helper.go
  examples/api-basic/api/v2/app_test.go
  examples/getting-started/rpc-style/apis/api.app.v1.json
  examples/getting-started/rpc-style/apis/api.storage.v1alpha1.json
  examples/getting-started/rpc-style/main.go
  middlewares/metrics/metrics.go
  nirvana.go
  plugins/apidocs/apidocs.go
  plugins/healthcheck/healthz.go
  plugins/profiling/profiling.go
  plugins/version/version.go
  service/builder/builder.go
  service/rest/builder.go
  service/rpc/builder.go
  service/types.go
  utils/api/api.go
  utils/api/definitions.go
  utils/api/utils.go
  utils/builder/builder.go
  utils/unittest/unittest.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#391 test(rpc): add unit test for rpc style api
  service/rpc/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#394 fix(*): remove the Summary field in RPCAction struct
  definition/rpc.go
  service/rpc/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#398 chore(*): add SimpleRPCDescriptor for convenience
  definition/helper.go
  middlewares/metrics/metrics.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#400 fix(utils): fix the counting logic of duplicate names
  utils/generators/golang/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#402 fix(*): make modifier ProduceAllIfProducesIsEmpty also modify ErrorProduces
  service/modfier_test.go
  service/modifier.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
